### ISSUE TITLE
Version defaults to main which can be unstable

### ISSUE THREAD

**Issue by davidsandilands** [voxpupuli/puppet-hdm#52]
**Is your feature request related to a problem? Please describe.**
The main branch of HDM is often in an unstable state or broken state and it can be confusing to new users when using the modules default for version

**Describe the solution you'd like**
A default version of latest HDM stable version

**Describe alternatives you've considered**
Maybe just documenting it clearly in the readme would help?

**Comment by tuxmea** [comment]
@davidsandilands can you please check if the PR is OK for you?
I removed the default value and added the link to HDM releases.

**Comment by davidsandilands** [comment]
Yup this looks good to me 👍
